# Generated by Django 5.1.3 on 2024-11-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nascimento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='quantia',
            new_name='quantity',
        ),
    ]
